services:
  recon_database:
    image: postgres:16
    container_name: recon_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  recon_app:
    image: recon_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - recon_database
      - redis
      - recon_tool
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  recon_tool:
    container_name: recon_tool
    build:
      context: .
      dockerfile: Dockerfile.tools
    expose:
      - "8001"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:7
    expose:
      - "6379"
    restart: unless-stopped

  worker_subdomains:
    build: .
    command: rq worker --url redis://redis:6379/0 subdomains
    depends_on:
      - redis
      - recon_database
      - recon_tool
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  worker_urls:
    build: .
    command: rq worker --url redis://redis:6379/0 urls
    depends_on:
      - redis
      - recon_database
      - recon_tool
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  pgdata:
