services:
  recon_database:
    image: postgres:16
    container_name: recon_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10

  recon_app:
    image: recon_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - recon_database
    env_file:
      - .env

  recon_tool:
    container_name: recon_tool
    build:
      context: .
      dockerfile: Dockerfile.tools
    ports:
      - "8001:8001"
    tty: true
    stdin_open: true

volumes:
  pgdata:
